### ISSUE TITLE
Allowing !findblock to also look for blocks owned by player and not only build by player

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer#2] opened 2020-03-31 13:33 UTC
Using findblock to check what refineries a player owned I was met with the following output : 

```
!findblock Refinery -player=CowMan-groupby=grid

Block of Player CowMan
19 74765055943807038 Refinery Outpost 2 - Owned by: CowMan [ECW]
Total: 19 Blocks
1 Grids checked
```

```
!findblock Refinery -player=CowMan
Block of Player CowMan
19 ECW CowMan
Total: 19 Blocks
1 Grids checked
```

CowMan owns 0 of the refineries on that grid. CowMan *does* own the grid itself, but 0 refineries. This is adverse to what I would expect

**Comment by LordTylus** [comment] 2020-03-31 15:20
Hi, Thank you for your report.

First of all !findblock Refinery -player=CowMan -groupby=grid
would be correct. (a space between playername and groupby was missing).

To clear up the misunderstanding. The PCU Transferrer in itself generally does not care for Ownership of blocks. 

The interesting Metric is the Authorship. 

So even if CowMan does not "own" the Blocks (when Looking at them in the Terminal) he is the Author of them. Because he originally built, or placed them. When looking at them with a Welder you should see the "Build by: CowMan" Label in the overlay. 

Since hes the author of the blocks the !findblocks command will display them, BlockType Limits will be taken from him by the game etc.

The Output above means:
On Grid "74765055943807038 Refinery Outpost 2" which is owned by CowMan [ECW] there are 19 Refineries build by CowMan

The Purpose of the Command is to find if other players "stole" limited blocks. I am often asked by players why they cannot build more drills (for example). So I check to see which grids contain the drills and to easily spot the Grids (which are owned by for example any other faction). 

Most of the time an other faction member used a share welding ship to build some stuff which will always set the same "Build by" information as they have themselves. 

So as far as I can tell its working as intended right now.

**Comment by kontu** [comment] 2020-03-31 15:29
Sorry the lost space was from sanitizing username.

That makes sense the way you explain it, just wasn't clear since transferring ownership (beyond just BuiltBy) is a large part of the plugin
Can I request  methods for both BuiltBy (existing) and OwnedBy lookups?

**Comment by LordTylus** [comment] 2020-03-31 15:34
Yeah transferring Ownership along with PCU was more a convenience method I added, because I was too lazy to always manually access the Terminal, unhide all blocks and transfer them over.

Using a command for that also has the benefit that I can use it via Discord Bridge without being logged into the server.

And yes you can request it as enhancement. Personally I don't see the need for that. But it should not be hard to implement. My idea would be to add new new parameter. 

!findblock Refinery -player=CowMan -groupby=grid -metric=owner (author would be default)

The same way I would add your other request to find blocks by type or subtype ID instead of blockpair name.

**Comment by LordTylus** [comment] 2020-04-03 19:49
As of v1.1.6.0 you can use

!findblock Refinery -player=CowMan -groupby=grid -metric=owner
if you want

note however not all blocks can be owned. you wont find any armor blocks by owner as they are unownable.

**Closed as completed by LordTylus** 2020-04-03 19:49 UTC
Labels: enhancement, not a bug
